esphome:
  name: esp-temp01
  platform: ESP8266
  board: nodemcu

wifi:
  networks:
  - ssid: !secret ssid
    password: !secret wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret key

ota:
  password: !secret ota_password

sensor:
  - platform: dht
    model: DHT22
    pin: D2
    temperature:
      name: "Basement Temperature"
      device_class: "temperature"
      state_class: "measurement"
    humidity:
      name: "Basement Humidity"
      device_class: "humidity"
      state_class: "measurement"
    update_interval: 60s
  - platform: wifi_signal
    name: "Basement WiFi Signal"
    update_interval: 60s
  - platform: uptime
    name: "Basement uptime seconds"
    id: uptime_s
        
binary_sensor:
  - platform: status
    name: "Basement Status"

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "Basement IP Address"
    ssid:
      name: "Basement SSID"
  - platform: template
    name: "Basement uptime"
    lambda: |-
      uint32_t dur = id(uptime_s).state;
      int dys = 0;
      int hrs = 0;
      int mnts = 0;
      if (dur > 86399) {
        dys = trunc(dur / 86400);
        dur = dur - (dys * 86400);
      }
      if (dur > 3599) {
        hrs = trunc(dur / 3600);
        dur = dur - (hrs * 3600);
      }
      if (dur > 59) {
        mnts = trunc(dur / 60);
        dur = dur - (mnts * 60);
      }
      char buffer[17];
      sprintf(buffer, "%ud %02uh %02um %02us", dys, hrs, mnts, dur);
      return {buffer};
    icon: mdi:clock-start

switch:
  - platform: restart
    name: "Basement Restart"