esphome:
  name: esp_lolin
  platform: ESP32
  board: lolin_d32_pro

wifi:
  domain: .local
  networks:
  - ssid: !secret ssid
    password: !secret wifi_password

debug:

logger:
  level: DEBUG
  
# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password

web_server:
  port: 80
  
sensor:
  - platform: wifi_signal
    name: "Lolin WiFi Signal"
    update_interval: 60s
  - platform: uptime
    name: "Lolin uptime seconds"
    id: uptime_s
        
binary_sensor:
  - platform: status
    name: "Lolin Status"
#  - platform: gpio
#    pin: GPIO14
#    name: "Lolin IRQ"
    
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "Lolin IP Address"
    ssid:
      name: "Lolin SSID"
  - platform: template
    name: "Lolin uptime"
    lambda: |-
      uint32_t dur = id(uptime_s).state;
      int dys = 0;
      int hrs = 0;
      int mnts = 0;
      if (dur > 86399) {
        dys = trunc(dur / 86400);
        dur = dur - (dys * 86400);
      }
      if (dur > 3599) {
        hrs = trunc(dur / 3600);
        dur = dur - (hrs * 3600);
      }
      if (dur > 59) {
        mnts = trunc(dur / 60);
        dur = dur - (mnts * 60);
      }
      char buffer[17];
      sprintf(buffer, "%ud %02uh %02um %02us", dys, hrs, mnts, dur);
      return {buffer};
    icon: mdi:clock-start

switch:
  - platform: restart
    name: "Lolin Restart"